namespace: default
imagePullPolicy: IfNotPresent
docker:
  repository: nkhank11

# Thêm configuration cho Zipkin
zipkinUrl: &zipkinUrl
  name: ZIPKIN_URL
  value: http://zipkin:9411

ingress:
  name: spring-petclinic-ingress
  host: petclinic.cloud
  apiGatewayName: api-gateway
  apiGatewayPort: 8080
  adminServiceName: admin-server
  adminServicePort: 9090
  eurekaServiceName: discovery-server
  eurekaServicePort: 8761

dependOnEureka: &dependOnEureka
  name: discovery-server
  port: 8761

configServerEnv: &configServerEnv
  name: CONFIG_SERVER_URL
  value: http://config-server:8888

defaultAutoscaling: &defaultAutoscaling
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  scaleUpStabilizationWindowSeconds: 60
  scaleDownStabilizationWindowSeconds: 300

services:
  config-server:
    ports:
      port: 8888
      targetPort: 8888
    image:
      name: spring-petclinic-config-server

  discovery-server:
    ports:
      port: 8761
      targetPort: 8761
    image:
      name: spring-petclinic-discovery-server
    depend_on: 
      name: config-server
      port: 8888
    env: 
      - *configServerEnv

  admin-server:
    ports:
      port: 9090
      targetPort: 9090
    image:
      name: spring-petclinic-admin-server
    depend_on: *dependOnEureka
    env: 
      - *configServerEnv
      - *zipkinUrl

  customers-service:
    ports:
      port: 8081
      targetPort: 8081
    image:
      name: spring-petclinic-customers-service
    depend_on: *dependOnEureka
    autoscaling:
      <<: *defaultAutoscaling
    env: 
      - *configServerEnv
      - *zipkinUrl  # Thêm Zipkin URL environment variable

  visits-service:
    ports:
      port: 8082
      targetPort: 8082
    image:
      name: spring-petclinic-visits-service
    depend_on: *dependOnEureka
    autoscaling:
      <<: *defaultAutoscaling
    env: 
      - *configServerEnv
      - *zipkinUrl

  vets-service:
    ports:
      port: 8083
      targetPort: 8083
    image:
      name: spring-petclinic-vets-service
    depend_on: *dependOnEureka
    autoscaling:
      <<: *defaultAutoscaling
    env: 
      - *configServerEnv
      - *zipkinUrl

  genai-service:
    ports:
      port: 8084
      targetPort: 8084
    image:
      name: spring-petclinic-genai-service
    depend_on: *dependOnEureka
    autoscaling:
      <<: *defaultAutoscaling
    env: 
      - *configServerEnv
      - *zipkinUrl

  api-gateway:
    ports:
      port: 8080
      targetPort: 8080
    image:
      name: spring-petclinic-api-gateway
    depend_on: *dependOnEureka
    autoscaling:
      <<: *defaultAutoscaling
    env: 
      - *configServerEnv
      - *zipkinUrl

  tracing-server:
    dockerRepository: openzipkin
    ports:
      port: 9411
      targetPort: 9411
    image:
      name: zipkin
    # Không cần CONFIG_SERVER_URL cho Zipkin
    env: []
