namespace: dev

services:
  config-server:
    image:
      tag: latest

  discovery-server:
    image:
      tag: latest

  admin-server:
    image:
      tag: latest

  customers-service:
    image:
      tag: latest

  visits-service:
    image:
      tag: latest

  vets-service:
    image:
      tag: latest

  genai-service:
    image:
      tag: latest

  api-gateway:
    image:
      tag: latest
      
  tracing-server:
    image:
      tag: latest

  grafana-server:
    image:
      name: spring-petclinic-grafana
      tag: latest
      pullPolicy: Always


  prometheus-server:
    image:
      name: spring-petclinic-prometheus
      tag: latest
