namespace: preview-abc-com

services:
  config-server:
    image:
      tag: v1.1

  discovery-server:
    image:
      tag: v1.1

  admin-server:
    image:
      tag: v1.1

  customers-service:
    image:
      tag: v1.1

  visits-service:
    image:
      tag: v1.1

  vets-service:
    image:
      tag: v1.1

  genai-service:
    image:
      tag: v1.1

  api-gateway:
    image:
      tag: v1.1
